
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Zap, Users, TrendingUp } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { Logo } from "@/components/shared/logo";

export default function LandingPage() {
  const features = [
    {
      icon: <Zap className="h-8 w-8 text-primary" />,
      title: "AI-Powered Suggestions",
      description: "Personalized micro-tasks generated by AI to fit your goals and schedule.",
    },
    {
      icon: <TrendingUp className="h-8 w-8 text-primary" />,
      title: "Track Your Progress",
      description: "Visualize your success with intuitive charts and celebrate your streaks.",
    },
    {
      icon: <Users className="h-8 w-8 text-primary" />,
      title: "Community Support",
      description: "Join challenges and share your journey with a supportive community.",
    },
    {
      icon: <CheckCircle className="h-8 w-8 text-primary" />,
      title: "Build Lasting Habits",
      description: "Turn small, consistent actions into lifelong positive changes.",
    },
  ];

  return (
    <div className="flex flex-col min-h-screen">
      <header className="py-4 px-6 sticky top-0 bg-background/80 backdrop-blur-md z-50 border-b">
        <div className="container mx-auto flex justify-between items-center">
          <Logo />
          <nav className="space-x-4">
            <Button variant="ghost" asChild>
              <Link href="/auth">Login</Link>
            </Button>
            <Button asChild className="bg-accent text-accent-foreground hover:bg-accent/90">
              <Link href="/auth?mode=signup">Sign Up</Link>
            </Button>
          </nav>
        </div>
      </header>

      <main className="flex-grow">
        {/* Hero Section */}
        <section className="py-20 md:py-32 text-center bg-gradient-to-br from-primary/10 via-background to-background">
          <div className="container mx-auto px-6">
            <Logo size="large" className="justify-center mb-6" />
            <h1 className="text-4xl md:text-6xl font-bold font-headline mb-6 text-foreground animate-slide-in-from-bottom [animation-delay:0.2s]">
              Build Better Habits with <span className="text-primary">AI</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto animate-slide-in-from-bottom [animation-delay:0.4s]">
              HabitAI helps you achieve your goals through personalized task suggestions, progress tracking, and community support. Start your journey to a better you, today!
            </p>
            <Button size="lg" asChild className="animate-slide-in-from-bottom [animation-delay:0.6s] shadow-lg transform hover:scale-105 transition-transform">
              <Link href="/auth?mode=signup">Get Started for Free</Link>
            </Button>
            <div className="mt-16 animate-slide-in-from-bottom [animation-delay:0.8s]">
              <Image
                src="/images/hero-ai-plant.png"
                alt="HabitAI dashboard preview with an AI generated plant image"
                width={800}
                height={450}
                className="rounded-lg shadow-2xl mx-auto border-4 border-primary/20"
                priority
              />
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-16 md:py-24 bg-background">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl md:text-4xl font-bold font-headline text-center mb-12 text-foreground">
              Everything you need to succeed
            </h2>
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {features.map((feature, index) => (
                <Card key={index} className="bg-card shadow-lg hover:shadow-xl transition-shadow duration-300">
                  <CardHeader>
                    <div className="mb-4 flex justify-center">{feature.icon}</div>
                    <CardTitle className="text-xl text-center font-headline">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription className="text-center">{feature.description}</CardDescription>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* How it works Section */}
        <section className="py-16 md:py-24 bg-primary/5">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl md:text-4xl font-bold font-headline text-center mb-16 text-foreground">How HabitAI Works</h2>
            <div className="grid md:grid-cols-3 gap-10 items-start">
              <div className="text-center">
                <div className="bg-primary text-primary-foreground rounded-full w-16 h-16 flex items-center justify-center text-2xl font-bold mx-auto mb-4 shadow-md">1</div>
                <h3 className="text-xl font-semibold mb-2 font-headline">Set Your Goal</h3>
                <p className="text-muted-foreground">Define the habit you want to build, like "exercise daily" or "read more books."</p>
              </div>
              <div className="text-center md:mt-8">
                <div className="bg-primary text-primary-foreground rounded-full w-16 h-16 flex items-center justify-center text-2xl font-bold mx-auto mb-4 shadow-md">2</div>
                <h3 className="text-xl font-semibold mb-2 font-headline">Get AI Tasks</h3>
                <p className="text-muted-foreground">Receive smart, actionable micro-tasks tailored to your preferences and schedule.</p>
              </div>
              <div className="text-center md:mt-16">
                <div className="bg-primary text-primary-foreground rounded-full w-16 h-16 flex items-center justify-center text-2xl font-bold mx-auto mb-4 shadow-md">3</div>
                <h3 className="text-xl font-semibold mb-2 font-headline">Track & Grow</h3>
                <p className="text-muted-foreground">Monitor your progress, build streaks, earn badges, and stay motivated.</p>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 text-center bg-accent">
          <div className="container mx-auto px-6">
            <h2 className="text-3xl md:text-4xl font-bold font-headline mb-6 text-accent-foreground">
              Ready to Transform Your Habits?
            </h2>
            <p className="text-lg text-accent-foreground/90 mb-8 max-w-xl mx-auto">
              Join thousands of users building better lives, one habit at a time.
            </p>
            <Button size="lg" variant="secondary" asChild className="bg-background text-foreground hover:bg-background/90 shadow-lg transform hover:scale-105 transition-transform">
              <Link href="/auth?mode=signup">Start Building Habits Today</Link>
            </Button>
          </div>
        </section>
      </main>

      <footer className="py-8 border-t bg-background">
        <div className="container mx-auto px-6 text-center text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} HabitAI. All rights reserved.</p>
          <div className="mt-2">
            <Link href="/privacy" className="hover:text-primary">Privacy Policy</Link> | <Link href="/terms" className="hover:text-primary">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
